### ISSUE TITLE
Example bug?

### ISSUE THREAD

**Issue by xaque208** [briandowns/jail#5]
https://github.com/briandowns/jail/blob/master/_examples/basic/main.go#L28

In reviewing this project and looking over the examples, I believe the above is just reading the host directory.  Correct me if I'm wrong.  In any case, I'd like to see an example where the jail was listed if that's not it.

**Comment by briandowns** [comment]
This example will read the root directory of the jail. The chroot option here puts the current process into the root of the jail.

**Comment by xaque208** [comment]
Which chroot option?  I'm just seeing that the call is `ioutil.ReadDir(".")`, which doesn't seem to reference the jail at all and just reads the current working directory.  Are you saying that the current directory is moved to the root of the jail?  If so, then the directory listing isn't actually made from within the jail process, correct?

**Comment by briandowns** [comment]
Apologies. It's `chdir` here: https://github.com/briandowns/jail/blob/master/_examples/basic/main.go#L19

What happens is that the process gets put into the jail however the process needs to be told to run in the jail filesystem.

**Comment by xaque208** [comment]
I see.  That's a little different than I was thinking.  I was thinking of something like a `j.Exec("ls")` or something, but maybe that's supported already.  So creating the object changes the current working directory based on that flag.  So creating a bunch of jail objects in one go might cause some conflict I suppose.

**Comment by briandowns** [comment]
Correct, there'd be conflict. You would need to have a manager another level up. The manager would need to control the execution of the binaries and decide which jails they go into or simply if they go into a jail.

My dream would be having the ability to execute Go routines in their own jails depending on needs.

**Comment by xaque208** [comment]
Okay, thanks for the explanation.
